<!-- Link Of CSS -->
<link rel="stylesheet" href="{{ asset_url('css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset_url('css/owl.theme.default.min.css') }}">
<link rel="stylesheet" href="{{ asset_url('css/owl.carousel.min.css') }}">
<link rel="stylesheet" href="{{ asset_url('css/animate.min.css') }}">
<link rel="stylesheet" href="{{ asset_url('css/remixicon.css') }}">
<link rel="stylesheet" href="{{ asset_url('css/boxicons.min.css') }}">
<link rel="stylesheet" href="{{ asset_url('css/iconsax.css') }}">
<link rel="stylesheet" href="{{ asset_url('css/metismenu.min.css') }}">
<link rel="stylesheet" href="{{ asset_url('css/simplebar.min.css') }}">
<link rel="stylesheet" href="{{ asset_url('css/calendar.css') }}">
<link rel="stylesheet" href="{{ asset_url('css/sweetalert2.min.css') }}">
<link rel="stylesheet" href="{{ asset_url('css/jbox.all.min.css') }}">
<link rel="stylesheet" href="{{ asset_url('css/editor.css') }}">
<link rel="stylesheet" href="{{ asset_url('css/font-awesome.min.css') }}">
<link rel="stylesheet" href="{{ asset_url('css/loaders.css') }}">
<link rel="stylesheet" href="{{ asset_url('css/header.css') }}">
<link rel="stylesheet" href="{{ asset_url('css/sidebar-menu.css') }}">
<link rel="stylesheet" href="{{ asset_url('css/footer.css') }}">
<link rel="stylesheet" href="{{ asset_url('css/style.css') }}">
<link rel="stylesheet" href="{{ asset_url('css/responsive.css') }}">
